- name: 取得資訊
  hosts: '{{host}}'
  become: true
  gather_facts: no
  vars:
    du_info: []
    du_latest_images: []
    du_need_deploy_list: []
  #no_log: true
  tasks: 
    - name: 取得DU資訊
      community.docker.docker_host_info:
        containers: yes
      register: container_info

    # - name: setfact
    #   set_fact:
    #     du_info: "{{ du_info + container_info.containers }}"

    - name: 取得cpe中運行的du部分資訊列
      set_fact:
        du_info: "{{ du_info +[{'container_name':item.Names[0],'image_ver':item.Image}] }}"
      loop: "{{ container_info.containers }}"
    
    - name: 比對有無新DU
      set_fact:
        du_need_deploy_list: "{{ du_latest_images | difference(du_info)}}"
    
    - include_tasks: /tasks-for-deploy/deploy-du.yml
      loop: "{{ du_need_deploy_list }}"
      loop_control:
        loop_var: new_du_item 

# - name: 比對與處理DU資訊
#   hosts: localhost
#   gather_facts: no
#   no_log: true
#   vars:
#     cpe_need_du_list: []
#     du_latest_images: []
#     d_info: []
#     du_need_deployed_info: []
#     hostlist: "{{ groups[host] }}"
#   tasks:
#     - include_tasks: get_du_info_list.yml
#       loop: "{{ hostlist }}"
#       loop_control:
#         loop_var: host_num

# - name: 部署DU
#   hosts: '{{host}}'
#   become: true
#   no_log: true
#   gather_facts: no
#   vars:
#     du_need_deployed_info: "{{ hostvars['localhost']['cpe_need_du_list'] }}"
#     deploy_info: []
#   tasks: 
#      c_name : "{{ new_du_item.container_name | trim('/') }}"

#     - include_tasks: deploy-du.yml
#       when: new_du_item.cpe_name == inventory_hostname
#       loop: "{{ du_need_deployed_info }}"
#       loop_control:
#         loop_var: new_du_item    
    
    
