---
- name: 設置ssh key於CPE
  hosts: "{{ host }}"
  become: true
  vars:
    - new_cpe_parameter: ""
  tasks:
    - name: 新增ssh key 到cpe
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', '/cpe_ssh_keys/{{host}}/cpeKey.pub') }}"
        
    - name: 安裝所需套件
      pip:
        name: pandas

    - name: 安裝 docker python library
      pip:
        name: docker
        
    - name: 設定參數
      setParameterValue:
        parameter_key: 
          - hostname: '{{host}}'
      register: set_parameter_result
    
    - name: 設定結果
      debug: msg="{{ set_parameter_result }}"
    
    - name: 運行periodic inform的container
      community.docker.docker_container:
        name: inform-2
        image: '{{ inform_periodic_latest_image }}'
        detach: yes
        auto_remove: no
        interactive: no
        privileged: no
        tty: no
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/vagrant/parameter:/parameter

#- name: 將該CPE的ssh key的私鑰路徑加入inventory
#  hosts: localhost
#  become: true
#  tasks:
#    - name:
#      ansible.builtin.lineinfile:
#        path: /etc/ansible/hosts
#        insertafter: "ansible_ssh_host={{ ansible_ip }}"
#        line:  ansible_ssh_private_key_file="{{ ssh_key_path }}"
     

        