- name: 更新DU
  hosts: '{{host}}'
  vars:
    old_ver_containers_info: []
    du_latest_images: []
    new_ver_containers_info: []
    port_list: []     
  tasks: 
    - name: 取得DU資訊
      community.docker.docker_host_info:
        containers: yes
      register: du_info

    - name: print result    
      debug:
        msg: "{{ du_info }}"
        
    - include_tasks: filter-image-ver.yml
      loop: "{{ du_latest_images }}"
      loop_control:
        loop_var: new_ver_image_item
    
    - include_tasks: container-port-format.yml
      loop: "{{ old_ver_containers_info }}"
      loop_control:
        loop_var: old_ver_containers_item    
    
    - name: print result
      debug:
        msg: "{{ item }}"
      loop: "{{ new_ver_containers_info }}"
    
    - include_tasks: update-du-ver.yml
      loop: "{{ new_ver_containers_info }}"
      loop_control:
        loop_var: new_ver_container_item
      
      


    



