---
- name: 運行ACS
  hosts: "{{ ACS_hostname }}"
  tasks:
    - name: 新增所需資料夾與檔案
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop: 
        - "{{ ansible_playbook_path }}"
        - "{{ du_info_path }}"
        - "{{ tmp_du_info_path }}"
        - "{{ cpe_ssh_keys_path }}"
        - "{{ ansible_host_path }}"

    - name: 新增所需文件
      ansible.builtin.file:
        path: "{{ item }}"
        state: touch
        mode: '0755'
      loop:
        - "{{ ansible_host_path }}/hosts"
        - "{{ ansible_host_path }}/ansible.cfg"

    - name: 複製playbook
      ansible.builtin.copy:
        src: "{{ workspace_playbook_loc }}"
        dest: "{{ ansible_playbook_path }}/"
        mode: '0755'

    - name: 運行ACS的container
      community.docker.docker_container:
        name: ACS
        image: 192.168.33.10:5000/inform-manage-server:latest
        detach: yes
        auto_remove: no
        interactive: yes
        privileged: no
        tty: yes
        ports: "{{ port_list }}"
        volumes:
          - "{{ ansible_playbook_path }}:/ansible_playbook"
          - "{{ du_info_path }}:/info"
          - "{{ tmp_du_info_path }}:/tmp"
          - "{{ cpe_ssh_keys_path }}:/cpe_ssh_keys"
          - "{{ ansible_host_path }}:/etc/ansible"